export enum DrawingListName {
    MAIN_DRAWING_LIST='MAIN_DRAWING_LIST',
    ARTIST_DETAILS_DRAWING_LIST='ARTIST_DETAILS_DRAWING_LIST',
    GALLERY_DETAILS_DRAWING_LIST='GALLERY_DETAILS_DRAWING_LIST'
}
